### ISSUE TITLE
Can't enter non-numeric SIP addresses.

### ISSUE THREAD

**Issue by sindastra** [whitequark/SIPCaller#1]
The input field prior to the '@' doesn't accept non-numeric values, while there are indeed non numeric addresses.

For example: username@example.com can not be dialed.

**Comment by whitequark** [comment]
Hmm, true. But the primary use case (for me) is dialing PSTN numbers. Any idea how to permit what you want without making that inconvenient?

**Comment by whitequark** [comment]
I suppose I could add a toggle, but it's kind of ugly...

**Comment by sindastra** [comment]
How about making it a simple text field so that the normal keyboard would pop up?

And about making it inconvenient to type in normal phone numbers: Why not create your own in-app numeric keyboard?

**Comment by whitequark** [comment]
> And about making it inconvenient to type in normal phone numbers: Why not create your own in-app numeric keyboard?

Because this is even uglier than having a toggle? I'm a programmer, not UI designer.

**Comment by sindastra** [comment]
> Because this is even uglier than having a toggle?

Why do you think that? There's nothing wrong with an in-app numeric keyboard.

> I'm a programmer, not UI designer.

Well, design-wise I'm imagining the number keys to have no background nor border. It would look like having the numbers directly on the background.

I'm no Android programmer, but I assume it should be possible to create a simple button with no background nor border? It would be a very simplistic design.

Unless you don't want to. Those are just suggestions.

**Comment by whitequark** [comment]
I do want to support this functionality (since it is perfectly valid to request and clearly useful), but I don't want to do this in a way that is ugly, and I have no real idea how to implement this in a non-ugly way... maybe the dialer can be embedded somehow?

**Comment by sindastra** [comment]
> and I have no real idea how to implement this in a non-ugly way... maybe the dialer can be embedded somehow?

Maybe I wasn't clear enough. My suggestion was to have the in-app dialer right under the address input.

Imagine having simple buttons for each key, but simply removing the buttons' borders and backgrounds. That way it would look like the keys are directly on the background. It would be a very simple design.

You'd have your input at the top, and simply the dialer right below it:

```
|---------------|
|   ====@====   |
|   1   2   3   |
|   4   5   6   |
|   7   8   9   |
|   *   0   #   |
| [call button] |
|---------------|
```

I'd also suggest to move the call button all the way down.

And the reason I am putting emphasis on removing the borders and background is this:

```
| [ 1 ] [ 2 ] [ 3 ] |    ->    |   1   2   3   |
```

It looks a lot cleaner that way.

**Comment by whitequark** [comment]
Implemented using an option.
